#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
source "${scriptDir}/config"

# sna(p) w(indow) t(op)/b(ottom)/l(eft)/r(ight)/t(op)l(eft)/t(op)r(ight)/b(ottom)l(eft)/b(ottom)r(ight)/c(enter) <WID> [.. <WID>]
function main(){
  local winPos=${1}
  shift
  local winIDs="${@}"

  local rootWin=$(lsw -r)
  local rootW=$(wattr w "${rootWin}")
  local rootH=$(wattr h "${rootWin}")

  local rootW=$((rootW - PAD_LEFT - PAD_RIGHT))
  local rootH=$((rootH - PAD_TOP - PAD_BOT))

  for winID in "${winIDs[@]}"; do
    case "${winPos}" in
      #         DISTANCE_LEFT           DISTANCE_TOP            WINDOW_WIDTH                      WINDOW_HEIGHT                     WINDOW_ID
      't')  wtp "${PAD_LEFT}"           "${PAD_TOP}"            "$((rootW - (2 * WIN_BORDER)))"   "$((rootH/2 - (2 * WIN_BORDER)))" "${winID}";;
      'b')  wtp "${PAD_LEFT}"           "$((PAD_TOP+rootH/2))"  "$((rootW - (2 * WIN_BORDER)))"   "$((rootH/2 - (2 * WIN_BORDER)))" "${winID}";;
      'l')  wtp "${PAD_LEFT}"           "${PAD_TOP}"            "$((rootW/2 - (2 * WIN_BORDER)))" "$((rootH - (2 * WIN_BORDER)))"   "${winID}";;
      'r')  wtp "$((PAD_LEFT+rootW/2))" "${PAD_TOP}"            "$((rootW/2 - (2 * WIN_BORDER)))" "$((rootH - (2 * WIN_BORDER)))"   "${winID}";;
      'tl') wtp "${PAD_LEFT}"           "${PAD_TOP}"            "$((rootW/2 - (2 * WIN_BORDER)))" "$((rootH/2 - (2 * WIN_BORDER)))" "${winID}";;
      'tr') wtp "$((PAD_LEFT+rootW/2))" "${PAD_TOP}"            "$((rootW/2 - (2 * WIN_BORDER)))" "$((rootH/2 - (2 * WIN_BORDER)))" "${winID}";;
      'bl') wtp "${PAD_LEFT}"           "$((PAD_TOP+rootH/2))"  "$((rootW/2 - (2 * WIN_BORDER)))" "$((rootH/2 - (2 * WIN_BORDER)))" "${winID}";;
      'br') wtp "$((PAD_LEFT+rootW/2))" "$((PAD_TOP+rootH/2))"  "$((rootW/2 - (2 * WIN_BORDER)))" "$((rootH/2 - (2 * WIN_BORDER)))" "${winID}";;
      'c')  wtp "$((PAD_LEFT+rootW/4))" "$((PAD_TOP+rootH/4))"  "$((rootW/2 - (2 * WIN_BORDER)))" "$((rootH/2 - (2 * WIN_BORDER)))" "${winID}";;
    esac
  done
}

main ${@}