#!/usr/bin/env bash

wallFile="${1}"

[[ ! -f "${wallFile}" ]] && wallFile=$(find "${HOME}/media/pictures/wallpapers" -maxdepth 1 -type f -exec file {} \; | awk -F: '{if ($2 ~/image/) print $1}' | sort -R | head -n 1)
setroot -z "${wallFile}"
echo "${wallFile}" > '/tmp/.wallpaper'