#!/usr/bin/env bash

dot-conf 'backup' 'on'
dot-conf 'verbose' 'off'

dot-link -g test/.config/bash 'bash'
dot-link -g test/.config/beets 'beets'
dot-link -g test/.config/bspwm 'bspwm'
dot-link -g test/.config/compton 'compton'
dot-link -g test/.config/dmenu 'dmenu'
dot-link -g test/.config/dunst 'dunst'
dot-link -g test/.config/font 'font'
dot-link -g test/.config/gtk-3.0 'gtk-3.0'
dot-link -g test/.config/luakit 'luakit/config'
dot-link -g test/.local/share/luakit 'luakit/share'
dot-link -g test/.config/mpd 'mpd'
dot-link -g test/.config/sxhkd 'sxhkd'
dot-link -g test/.config/mimeapps.list 'system/mimeapps.list'
dot-link -g test/.config/user-dirs.dirs 'system/user-dirs.dirs'
dot-link -g test/.config/fontconfig/conf.d/fonts.conf 'system/fonts.conf'
dot-link -g test/.vim 'vim'
dot-link -g test/.Xresources 'system/Xresources'
dot-link -g test/.xinitrc 'system/xinitrc'
dot-link -g test/.bashrc 'bash/bashrc'
dot-link -g test/.bash_profile 'bash/profile'

#dot-link -g -e test/ssh 'ssh'
