#!/usr/bin/env bash

dot-conf 'backup' 'on'
dot-conf 'verbose' 'off'

dot-link -g ~/.config/bash 'bash'
dot-link -g ~/.config/beets 'beets'
dot-link -g ~/.config/bspwm 'bspwm'
dot-link -g ~/.config/compton 'compton'
dot-link -g ~/.config/dmenu 'dmenu'
dot-link -g ~/.config/dunst 'dunst'
dot-link -g ~/.config/font 'font'
dot-link -g ~/.config/gtk-3.0 'gtk-3.0'
dot-link -g ~/.config/luakit 'luakit/config'
dot-link -g ~/.local/share/luakit 'luakit/share'
dot-link -g ~/.config/mpd 'mpd'
dot-link -g ~/.config/sxhkd 'sxhkd'
dot-link -g ~/.config/mimeapps.list 'system/mimeapps.list'
dot-link -g ~/.config/user-dirs.dirs 'system/user-dirs.dirs'
dot-link -g ~/.config/fontconfig/conf.d/fonts.conf 'system/fonts.conf'
dot-link -g ~/.vim 'vim'
dot-link -g ~/.Xresources 'system/Xresources'
dot-link -g ~/.xinitrc 'system/xinitrc'
dot-link -g ~/.bashrc 'bash/bashrc'
dot-link -g ~/.bash_profile 'bash/profile'

#dot-link -g -e ~/ssh 'ssh'
