#!/usr/bin/env bash

# Write xresource colors to variables
eval "$(xres2var)"

bspc config active_border_color "${base05}"
bspc config focused_border_color "${base0F}"
bspc config normal_border_color "${base03}"

bspc config top_padding "${PAD_TOP}"
bspc config border_width "${WIN_BORDER}"
bspc config window_gap "${WIN_GAP}"

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# TODO: Fix this ugly workaround!
if [[ ! -f "/tmp/.desktop" ]]; then
 #echo "" > /tmp/.desktop
 echo -ne ''
else
  #bspc monitor "${primaryDisplay}" --reset-desktops 1 2 3 4 5 6 7 8 9 0
  # TODO: Fix this ugly workaround!
  currentDesktop=$(cat /tmp/.desktop)

  # TODO: Fix this ugly workaround!
  bspc desktop -f "${currentDesktop}"
fi

primaryDisplay=$(xrandr | grep primary | awk -F ' ' '{print $1}')
bspc monitor "${primaryDisplay}" --reset-desktops          