#!/usr/bin/env bash

[[ ! $(pgrep 'sxhkd') ]] && sxhkd &
[[ ! $(pgrep 'dunst') ]] && dunst &
[[ ! $(pgrep 'compton') ]] && compton -b
[[ ! $(pgrep 'mpd') ]] && mpd &
[[ ! $(pgrep 'gpg-agent') ]] && gpg-connect-agent reloadagent /bye