#!/usr/bin/env bash
# Read more about it on
# https://github.com/baskerville/sxhkd/blob/master/parse.c#L384

#
# wm independent hotkeys
#

# terminal emulator
super + Return
  termite

super + Home
  nautilus

super + period
  ~/.config/bash/scripts/dmenu-fm

super + comma
  ~/.config/bash/scripts/dmenu-mp

# program launcher
super + space
  ~/.config/bash/scripts/dmenu-ex

super + ctrl + space
  ~/.config/bash/scripts/dmenu-pw

# make sxhkd reload its configuration files:
super + Escape
  pkill -USR1 -x sxhkd

# quit bspwm normally
super + alt + Escape
  ~/.config/bspwm/power/logoff

# shut down computer
super + ctrl + s
  ~/.config/bspwm/power/shutdown

# Hibernate computer
#super + ctrl + h
#  ~/.config/bspwm/power/hibernate

# lock screen
super + ctrl + o
  ~/.config/bspwm/power/lock

# suspend computer
super + ctrl + p
  ~/.config/bspwm/power/suspend

#
# bspwm hotkeys
#

# close and kill
super + {_,shift + }w
  bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
  bspc desktop -l next

# if the current node is automatic, send it to the last manual, otherwise pull the last leaf
super + y
  bspc query -N -n focused.automatic && bspc node -n last.!automatic || bspc node last.leaf -n focused

# swap the current node and the biggest node
super + g
  bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
  bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {x,y,z}
  bspc node -g {locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
  bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
  bspc node -f @{parent,brother,first,second}

# focus the next/previous node
super + {_,shift + }c
  bspc node -f {next,prev}

# focus the next/previous desktop
super + bracket{left,right}
  bspc desktop -f {prev,next}

# focus the last node/desktop
super + {grave,Tab}
  bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
  bspc wm -h off; \
  bspc node {older,newer} -f; \
  bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
  bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
  bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
  bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
  bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
  bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# resize tiled/floating
#

# expand the tiled space in the given direction
super + alt + {h,j,k,l}
  bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract the tiled space in the given direction
super + alt + shift + {h,j,k,l}
  bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Right,Up,Down}
  xdo move {-x -20,-x +20,-y -20,-y +20}
  #bspc node -v {-20 0,0 20,0 -20,20 0}

# resize window
alt + shift + {Left,Right,Up,Down}
    xdo resize {-w -20,-w +20,-h -20,-h +20}

#
# pointer focus/move/resize
#

# focus
~button1
  bspc pointer -g focus

# start move/resize
super + button{1-3}
  ; bspc pointer -g {move,resize_side,resize_corner}

# end move/resize
super + @button{1-3}
  bspc pointer -u

#bspc config -d focused window_gap `echo "$(bspc config -d focused window_gap) {+,-}5" | bc -l`-
## Gap Resizing

## Audio Volume Keys
XF86AudioRaiseVolume
  amixer -q sset Master 5%+

XF86AudioLowerVolume
  amixer -q sset Master 5%-

XF86AudioMute
  amixer -q sset Master toggle

## Audio Playback Keys
{XF86AudioPrev, XF86AudioNext, XF86AudioPlay}
  playerctl {previous,next,play-pause}

## Brightness Keys
XF86MonBrightnessUp
  xbacklight -inc 10

XF86MonBrightnessDown
  xbacklight -dec 10

# Reload displays
super + d
  rm /tmp/.displays

# Start screen recording
ctrl + alt + r
  ~/.config/bash/scripts/record

# Stop screen recording
ctrl + alt + x
  pkill -f 'x11grab'

# screenshot
@Print
  ~/.config/bash/scripts/scrot

ctrl + @Print
  ~/.config/bash/scripts/scrot 'window'

ctrl + shift + @Print
  ~/.config/bash/scripts/scrot 'area'

# change wallpaper and create theme from it
ctrl + shift + w
  ~/.config/bspwm/change_theme 'y'

super + alt + {w,s,a,d,q,e,z,x,c}
  snaw {t,b,l,r,tl,tr,bl,br,c} $(pfw)

#super + {Home,PageUp,End,PageDown}
#  movw l {-,+,-,+} 10px $(pfw); \
#  movw u {-,-,+,+} 10px $(pfw)