#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
scriptName=$(basename $0)
source "${scriptDir}/config"

function usage(){
  cat <<EOF
  ${scriptName} <WID> [.. <WID>]

  Destroy window
EOF
  exit 1
}

function main(){
  local winIDs="${@}"

  [[ "$#" -eq 0 ]] && >&2 usage

  for winID in "${winIDs[@]}"; do
    # Skip non-existing windows
    [[ $(wattr "${winID}") ]] && continue
    killwa "${winID}"

    local tagIDs=$(cd /tmp/.wm/tags && ls */${winID} 2>/dev/null | xargs dirname | sort -u)

    # Skip tag deletion if no tag was found
    [[ $? -gt 0 ]] && continue

    # Continue with tag deletion
    for tagID in "${tagIDs}"; do
      "${scriptDir}/tagw" -t "${tagID}" -a del -w "${winID}"
    done
  done
}

main "${@}"