#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
scriptName=$(basename $0)
source "${scriptDir}/config"

function usage(){
  cat <<EOF
  ${scriptName} <WID> [.. <WID>]

  Enforce window focus
EOF
  exit 1
}

function main(){
  local focID=$(pfw)

  #wattr "${focID}" && exit 0 || notify-send "Focus lost!"

  # Focus previous window if possible
  wattr "${focID}" || focID=$("${scriptDir}/fndw" -h p)

  # Focus first window if possible
  wattr "${focID}" || focID=$("${scriptDir}/fndw" -h l)

  # Focus window if we have any
  wattr "${focID}" && "${scriptDir}/stwf" "${focID}"
}

main "${@}"