#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
scriptName=$(basename $0)
source "${scriptDir}/config"

function usage(){
  cat <<EOF
  ${scriptName} <WID> [.. <WID>]

  Enforce window focus
EOF
  exit 1
}

function main(){
  local focID=$(pfw)

  # If a focused window exists, skip
  wattr "${focID}" && exit 0

  # Focus previous window if possible
  focID=$("${scriptDir}/fndw" -h p)
  wattr "${focID}" && "${scriptDir}/stwf" "${focID}" && exit 0

  # Focus last window if possible
  focID=$("${scriptDir}/fndw" -h l)
  wattr "${focID}" && "${scriptDir}/stwf" "${focID}" && exit 0

  exit 1
}

main "${@}"