#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
scriptName=$(basename $0)
source "${scriptDir}/config"

function usage(){
cat <<EOF
  ${scriptName} <options>

  Find windows

    -a  Action (add|delete|toggle|set|clear|show|hide|close)
    -t  Tag(s)
    -w  Window(s)
    -d  Debug (cli|popup)
EOF
  exit 1
}

function main(){
  local OPTIND

  local actType=''
  local tagIDs=''
  local winIDs=''
  local hasWin=0

  while getopts "a:d:t:w:" opt; do
    case $opt in
      a) actType="${OPTARG}";;
      d) debug="${OPTARG}";;
      t) tagIDs="${OPTARG}";;
      w)
        hasWin=1
        winIDs="${OPTARG}"
      ;;
    esac
  done

  [[ -z "${actType}" ]] && usage
  
  for tagID in "${tagIDs}"; do
    local tagDir="${wmTags}/${tagID}"
    local tagState="${wmTags}/${tagID}.state"

    if [[ "${hasWin}" -eq 1 ]]; then
      for winID in "${winIDs}"; do
        local winAct="${actType}"

        if [[  "${winAct}" == 's' ]] || [[ "${winAct}" == 'set' ]]; then
          [[ -d "${tagDir}" ]] && rm -rf "${tagDir}"
        elif [[  "${winAct}" == 't' ]] || [[ "${winAct}" == 'toggle' ]]; then
          [[ -f "${tagDir}/${winID}" ]] && winAct='d' || winAct='a'
        fi

        [[ ! -d "${tagDir}" ]] && mkdir -p "${tagDir}"

        case "${winAct}" in
          a|add|s|set) [[ ! -f "${tagDir}/${winID}" ]] && touch "${tagDir}/${winID}";;
          c|clear) [[ -d "${tagDir}" ]] && rm -rf "${tagDir}";;
          d|del) [[ -f "${tagDir}/${winID}" ]] && rm "${tagDir}/${winID}";;
        esac
      done
    else
      local tagAct="${actType}"

      if [[ "${tagAct}" == 't' ]] || [[ "${tagAct}" == 'toggle' ]]; then
        local stateTxt=$(head -n 1 "${tagState}")
        local visState=$(echo "${stateTxt}" | cut -d ';' -f 1)

        if [[ "${visState}" == 'v' ]]; then
          tagAct="h"
        else
          tagAct='s'
        fi
      fi

      case "${tagAct}" in
        h|hide) [[ -f "${tagState}" ]] && sed -i 's/v/h/g' "${tagState}" && "${scriptDir}/fxfw" -t "${tagID}" -c 'mapw -u ';;
        s|show) [[ -f "${tagState}" ]] && sed -i 's/h/v/g' "${tagState}" && "${scriptDir}/fxfw" -t "${tagID}" -c 'mapw -m ';;
        c|close) [[ -d "${tagDir}" ]] && "${scriptDir}/fxfw" -t "${tagID}" -c "${scriptDir}/desw " && rm -rf "${tagDir}" && rm "${tagState}";;
      esac
    fi

    # Remove tag if no more windows are mapped to it
    [[ $(find "${tagDir}" -maxdepth 0 -type d -empty 2>/dev/null) ]] && rm -rf "${tagDir}" && rm "${tagState}"

    # Add state file if tag has windows but no state file
    [[ -d "${tagDir}" ]] && [[ ! -f "${tagState}" ]] && echo 'v;' > "${tagState}"
  done
}

main ${@}