#!/usr/bin/env bash

#
# bspwm hotkeys
#

# Close/Kill window
super + {_,shift + }Escape
  bspc node -{c,k}

# Focus window west/east/north/south
super +{a,d,w,s}
  bspc node -f,s {west,east,north,south}

# Focus prev/next/first/last window
super + {q,e,y,x}
  bspc node -f {prev,next,first,last}

# Move window left/right/up/down
super + {Left,Right,Up,Down}
  xdo move {-x -10,-x +10,-y -10,-y +10}

# Snap windows
super + alt + {w,s,a,d,q,e,y,x,c}
  snaw {t,b,l,r,tl,tr,bl,br,c} $(pfw)

# Resize window
super + ctrl + {Left,Right,Up,Down}
  xdo resize {-w -10,-w +10,-h -10,-h +10}

# Set window mode to tiled/pseudo_tiled/floating/fullscreen
super + shift + {y,x,d,f}
  bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# Focus or send to specific desktop
super + {_,shift + }{1-9,0}
  bspc {desktop -f,node -d} '^{1-9,10}'

# Focus on click
~button1
  bspc pointer -g focus