#!/bin/bash

echo 'Reading ~/.xinitrc' > ~/.xinit.log

if [[ -f "${HOME}/.Xresources" ]]; then
  echo 'Merging .xResources' >> ~/.xinit.log
  xrdb -merge "${HOME}/.Xresources"
fi

echo 'Starting daemons' >> ~/.xinit.log
#/usr/bin/VBoxClient-all 2>&1 >> ~/.xinit.log &

echo 'Setting cursor-type' >> ~/.xinit.log
xsetroot -cursor_name left_ptr &

# Configure monitor power management: standby / suspend / off in seconds
echo 'Setting dpms' >> ~/.xinit.log
xset dpms 600 1200 1800 &

#~/code/shell/awde/src/statusbar.bash &

rm /tmp/.desktop
rm /tmp/.displays
rm /tmp/.wallpaper

echo 'Starting Window-Manager' >> ~/.xinit.log

# WORKAROUND FIX ME!
(sleep 2 && bash ~/.config/bspwm/bspwmrc) &

~/dotfiles/_ui/login 'bspwm'
exec bspwm 1> ~/.bspwm.out 2> ~/.bspwm.err
#-c ~/.config/bspwm/bspwmrc

#rm ~/.config/howm/sxhkdrc
#ln -s ~/.config/howm/sxhkdrc_normal ~/.config/howm/sxhkdrc
#sxhkd -c ~/.config/howm/sxhkdrc &
#exec ~/.config/howm/bar

#~/dotfiles/_ui/login &
#exec ~/dotfiles/wm/xblock
