#!/usr/bin/env bash

uuidList="${HOME}/.pastebin.list"

[[ -s "${uuidList}" ]] || echo "[INFO] There are no pastes!"

#awk -F ';' '{print "uuid: "$1"file: "$2"date: "$3;}' "${uuidList}"
awk -F ';' '{print "uuid: "$1"\nfile: "$2"\ndate: "$3"\n\n";}' "${uuidList}"