#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
scriptName=$(basename $0)

main(){
  local l=$(realpath -P "${1}")
  local r=$(realpath -P "${2}")

  mkdir -p '/tmp/theme'
  cd '/tmp/theme'

  local c=$("${scriptDir}/merge-colors" "${l}" "${r}")
  
  echo "${c}" | "${scriptDir}/colors2palette"
  echo "${c}" | "${scriptDir}/colors2preview"
}

main ${@}