#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
scriptName=$(basename $0)

[[ -z "${1}" ]] && exit 1

main(){
  [[ ! -d "${HOME}/themes/desktop/${1}" ]] && return 1

  source "${HOME}/themes/desktop/${1}/settings"

  echo "Wallpaper: \"${wallpaper}\""
  echo "Colorscheme: \"${colorscheme}\""
  echo "Merge Colors: \"${mergecolors}\""

  [[ -d "${HOME}/themes/loaded" ]] && rm "${HOME}/themes/loaded"/* || mkdir -p "${HOME}/themes/loaded"

  ln -s "${wallpaper}" "${HOME}/themes/loaded/wallpaper"

  for f in "${colorscheme}"/*; do
    ln -s "${f}" "${HOME}/themes/loaded/$(basename ${f})"
  done

  if [[ ! -z "${mergecolors}" ]]; then
    mv "${HOME}/themes/loaded/palette.txt" "${HOME}/themes/loaded/color-palette.txt"
    ln -s "${mergecolors}/palette.txt" "${HOME}/themes/loaded/merge-palette.txt"
    rm "${HOME}/themes/loaded/preview.png"

    local p=$("${scriptDir}/merge-colors" "${HOME}/themes/loaded/merge-palette.txt" "${HOME}/themes/loaded/color-palette.txt")
    (cd "${HOME}/themes/loaded" && echo "${p}" | "${scriptDir}/colors2palette")
    (cd "${HOME}/themes/loaded" && echo "${p}" | "${scriptDir}/colors2preview")
  fi

  echo "${wallpaper};${colorscheme};${mergecolors}" > "${HOME}/themes/loaded/generated"
}

main ${@}
