#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
scriptName=$(basename $0)

[[ -z "${1}" ]] && exit 1

main(){
  [[ ! -d "${HOME}/styles/desktop/${1}" ]] && return 1

  source "${HOME}/styles/desktop/${1}/settings"

  wallpaper="${wallpaper:-default}"
  colorscheme="${colorscheme:-default}"
  mergecolors="${mergecolors:-none}"
  gtkscheme="${gtkscheme:-default}"
  icontheme="${fontscheme:-default}"
  fontscheme="${fontscheme:-default}"
  dominance="${dominance:-auto}"

  echo "Wallpaper: \"${wallpaper}\""
  echo "Colorscheme: \"${colorscheme}\""
  echo "Merge Colors: \"${mergecolors}\""

  [[ -d "${HOME}/styles/cache" ]] && rm "${HOME}/styles/cache"/* || mkdir -p "${HOME}/styles/cache"

  ln -s "${wallpaper}" "${HOME}/styles/cache/wallpaper"

  for f in "${colorscheme}"/*; do
    ln -s "${f}" "${HOME}/styles/cache/$(basename ${f})"
  done

  if [[ ! -z "${mergecolors}" ]]; then
    mv "${HOME}/styles/cache/palette.txt" "${HOME}/styles/cache/color-palette.txt"
    ln -s "${mergecolors}/palette.txt" "${HOME}/styles/cache/merge-palette.txt"
    rm "${HOME}/styles/cache/preview.png"

    local p=$("${scriptDir}/merge-colors" "${HOME}/styles/cache/merge-palette.txt" "${HOME}/styles/cache/color-palette.txt")
    (cd "${HOME}/styles/cache" && echo "${p}" | "${scriptDir}/colors2palette")
    (cd "${HOME}/styles/cache" && echo "${p}" | "${scriptDir}/colors2preview")
  fi

  echo "${wallpaper};${colorscheme};${mergecolors}" > "${HOME}/styles/cache/generated"
}

main ${@}
