#!/usr/bin/env bash
# Read more about it on
# https://github.com/baskerville/sxhkd/blob/master/parse.c#L384

# --------------------------------------------------------
# wmutils bindings
# --------------------------------------------------------

# Kill window
super + Escape
  killwa $(pfw)
  #kill $(xprop -id $(pfw) | grep PID | cut -b25-)

# foc(us) w(indow) l(eft)/r(ight)/u(p)/d(own)/p(rev)/n(ext)
# Example focw u
super + {a,d,w,s}
  ~/dotfiles/wm/new_utils/stwf $(~/dotfiles/wm/new_utils/fndw -p {l,r,u,d})
super + {q,e,z,x}
  ~/dotfiles/wm/new_utils/stwf $(~/dotfiles/wm/new_utils/fndw -h {p,n,f,l})
#super + {a,d,w,s,q,e,z,x}
#  focw {l,r,u,d,p,n,b,e}

super + shift + m
  focw e

# mov(e) w(indow) l(eft)/r(ight)/u(p)/d(own) inc(+)/dec(-)/to(=) ?px/?% <WID> [.. <WID>]
# Example: movw d 5% $(pfw)
super + {Left,Right,Up,Down}
  movw {l,r,u,d} + 10px $(pfw)
#super + {Home,PageUp,End,PageDown}
#  movw l {+,-,+,-} 10px $(pfw) & \
#  movw u {+,+,-,-} 10px $(pfw)

# tel(eport) w(indow) <x> <y> <z> <WID> [.. <WID>]
# Example: telw 0 250 0 $(pfw)

# res(ize) w(indow) l(eft)/r(ight)/u(p)/d(own)/h(eight)/w(idth) inc(+)/dec(-)/to(=) ?px/?% <WID> [.. <WID>]
# Example: resw w + 5% $(pfw)
super + ctrl + {Left,Right,Up,Down}
  resw {l,r,u,d} + 10px $(pfw)
#super + shift + {Left,Right,Up,Down}
#  resw {l,r,u,d} - 10px $(pfw)

# mod(ify) w(indow) h(ide)/(m)a(ximize)/d(efault)/f(ullscreen) <WID> [.. <WID>]
# Example: modw a $(pfw)
super + shift + {y,x,d,f}
  modw {h,a,d,f} $(pfw)

# tag w(indow) <tag> add(+)/delete(-)/toggle(?)/set(=) <WID> [.. <WID>]
super + ctrl + {1-9}
  tagw {1-9} ? $(pfw)

# p(erform) t(agged) w(indow) a(ction) <tag> <cmd>
# Example: ptwa 0 killw
super + {1-9}
  ptwa {1-9} mapw -t; \
  ~/dotfiles/wm/new_utils/efwf
#super + shift + {1-9}
#  ptwa {1-9} killwa; \
#  tagc {1-9}

# mo(dify) w(indow) s(tacking order) inc(+)/dec(-)/to(=)/f(ront)/b(ack) ? <WID> [.. <WID>]
# Example: mows + 1 $(pfw)
#super + shift + {e,q}
#  mows {+,-} 1 $(pfw)
#super + shift + {pageUp,pageDown}
#  mows {f,b} $(pfw)

# sna(p) w(indow) t(op)/b(ottom)/l(eft)/r(ight)/t(op)l(eft)/t(op)r(ight)/b(ottom)l(eft)/b(ottom)r(ight)/c(enter) <WID> [.. <WID>]
# Example: snaw tl $(pfw)
super + alt + {w,s,a,d,q,e,z,x,c}
  snaw {t,b,l,r,tl,tr,bl,br,c} $(pfw)

# gro(up) w(indow) <GID|all> add(+)/del(-)/set(=) <WID> [.. <WID>]
# Example: grow 0 + $(pfw)
#super + ctrl + {0-9}
#  grow {0-9} + $(pfw)
#super + shift + {0-9}
#  grow {0-9} - $(pfw)

# mod(ify) g(roup) <GID|all> s(how)/h(ide)/t(oggle)/c(lear)
# Example: modg 0 s
#super + alt + {0-9}
#  modg {0-9} t
#super + alt + {pageUp,pageDown}
#  modg all {s,h}

# b(ac)k(u)p g(roup) <GID> [.. <GID>]
#super + Insert; {0-9}
#  bkpg {0-9}

# r(e)st(ore) g(roup) <GID> [.. <GID>]
#super + Delete; {0-9}
#  rstg {0-9}

# ch(ange) w(indow) l(ayout) t(ile)/f(loating)/m(onocycle)
# Example: chwl t
#super + alt + {t,f,r}
#  chwl {t,f,m}
  
# --------------------------------------------------------
# Other bindings
# --------------------------------------------------------

# Lock, Logoff, Shutdown, Hibernate, Reboot
super + shift + {k,l,n,h,o}
  {lkur,lour,sdpc,hnpc,rbpc}

# Reload bindings
super + shift + comma
  killall -USR1 sxhkd; \
  notify-send 'Restarted "sxhkd".'
   
super + Return
  termite
  
#super + Home
#  nautilus

super + period
  ~/.config/bash/scripts/dmenu-fm

super + comma
  ~/.config/bash/scripts/dmenu-mp

# program launcher
super + space
  ~/.config/bash/scripts/dmenu-ex

super + ctrl + space
  ~/.config/bash/scripts/dmenu-pw

## Audio Volume Keys
XF86AudioRaiseVolume
  amixer -q sset Master 5%+

XF86AudioLowerVolume
  amixer -q sset Master 5%-

XF86AudioMute
  amixer -q sset Master toggle

## Audio Playback Keys
{XF86AudioPrev, XF86AudioNext, XF86AudioPlay}
  playerctl {previous,next,play-pause}

## Brightness Keys
XF86MonBrightnessUp
  xbacklight -inc 10

XF86MonBrightnessDown
  xbacklight -dec 10

# Reload displays
#super + d
#  rm /tmp/.displays

# Start screen recording
ctrl + alt + r
  ~/.config/bash/scripts/record

# Stop screen recording
ctrl + alt + x
  pkill -f 'x11grab'

# screenshot
{_,ctrl +,shift +} @Print
  ~/.config/bash/scripts/scrot {_,window,area}

# change wallpaper and create theme from it
#ctrl + shift + w
#  ~/.config/bspwm/change_theme 'y'

#super + !button1