#!/usr/bin/env bash

set -e

# mov(e) w(indow) l(eft)/r(ight)/u(p)/d(own) inc(+)/dec(-)/to(=) ?px/?% <WID> [.. <WID>]

function main(){
  local moveDir=${1} # l|r|u|d
  local moveMod=${2} # +|-|=
  local moveVal=${3} # px|%
  shift; shift; shift
  local winIDs="${@}"

  for winID in "${winIDs[@]}"; do

  done
}

main ${@}