#!/usr/bin/env bash

# KEY_PRESS .......... 2
# KEY_RELEASE ........ 3
# BUTTON_PRESS ....... 4
# BUTTON_RELEASE ..... 5
# MOTION_NOTIFY ...... 6
# ENTER_NOTIFY ....... 7
# LEAVE_NOTIFY ....... 8
# FOCUS_IN ........... 9
# FOCUS_OUT .......... 10
# KEYMAP_NOTIFY ...... 11
# EXPOSE ............. 12
# GRAPHICS_EXPOSURE .. 13
# NO_EXPOSURE ........ 14
# VISIBILITY_NOTIFY .. 15
# CREATE_NOTIFY ...... 16
# DESTROY_NOTIFY ..... 17
# UNMAP_NOTIFY ....... 18
# MAP_NOTIFY ......... 19
# MAP_REQUEST ........ 20
# REPARENT_NOTIFY .... 21
# CONFIGURE_NOTIFY ... 22
# CONFIGURE_REQUEST .. 23
# GRAVITY_NOTIFY ..... 24
# RESIZE_REQUEST ..... 25
# CIRCULATE_NOTIFY ... 26
# CIRCULATE_REQUEST .. 27
# PROPERTY_NOTIFY .... 28
# SELECTION_CLEAR .... 29
# SELECTION_REQUEST .. 30
# SELECTION_NOTIFY ... 31
# COLORMAP_NOTIFY .... 32
# CLIENT_MESSAGE ..... 33
# MAPPING_NOTIFY ..... 34
# GE_GENERIC ......... 35

eval "$(xres2var)"

function checkWindow(){
  local winName="${1}"
  local winClass="${2}"
  local winID="${3}"

  [[ "${winName}" == 'bar' ]] && ignw -s "${winID}"; return 1
  [[ "${winClass}" == 'dmenu' ]] && ignw -s "${winID}"; return 1
  [[ "${winClass}" == 'Dunst' ]] && ignw -s "${winID}"; return 1
}

function setupWindow(){
  local winID="${1}"
  local color="0x$(echo "${base0A}" | tr -d '#')"
  
  winName=$(xprop -id "${winID}" WM_NAME | cut -d '"' -f 2)
  winClass=$(xprop -id "${winID}" WM_CLASS | cut -d '"' -f 2)

  [[ ! $(checkWindow "${winName}" "${winClass}" "${winID}") ]] && return 1

  # o: wattr returns 0 if the override_redirect 
  #  attribute is set on the window
  [[ $(wattr o "${winID}") ]] && return 1

  [[ $(pgrep 'bspwm') ]] && bspc node -t floating

  chwb -c "${color}" -s "${WIN_BORDER}" "${winID}"
  [[ "${winClass}" == 'hedgewars' ]] && modw a "${winID}"; return
  [[ "${winClass}" == 'hwengine' ]] && modw a "${winID}"; return

  #return

  #wmp -a $(wattr xy "${winID}") # move the mouse cursor to
  #wmp -r "$((winW /2))" "$((winH /2))" # .. its bottom right corner
  
  snaw c "${winID}"

  #notify-send "${winID} <> $(pfw)"
}

function mapWindow(){
  local winID="${1}"

  [[ $(wattr o "${winID}") ]] && continue

  wtf "${winID}"
}

function closeWindow(){
  [[ $(wattr "$(pfw)") ]] && return

  focw p
}

#function closeWindow(){
#  focw p
#  echo
#}

export -f setupWindow

function main(){
  wew | while IFS=':' read eventID winID; do
    case ${eventID} in
      16) setupWindow "${winID}";;
      #19) mapWindow "${winID}";;
      #18) closeWindow "${winID}";;
    esac
  done
}

main ${@}