#!/usr/bin/env bash

prog="${1:-xevents}"

while :; do
  #[[ $(pgrep -f "${prog}") ]] && kill $(pgrep -f "${prog}")
  "${HOME}/dotfiles/wm/${prog}"
  sleep 1s;
  notify-send -u 'low' "Restarting \"${prog}\"."
done
