#!/usr/bin/env bash

# Regain control of PATH inside sudo
alias sudo='sudo env PATH=$PATH'

## Colorize the ls output ##
alias ls='ls --color=auto'
 
## Use a long listing format ##
alias ll='ls -la'
 
## Show hidden files ##
alias l.='ls -d .* --color=auto'

## Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'
 
# confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
 
# Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# become root #
alias root='sudo -i'
alias su='sudo -i'

# Resume wget by default #
alias wget='wget -c'

# Git stuff #
alias ga='git add'
alias gp='git push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'

alias mpg='mpv --profile=pseudo-gui &'

alias xmt='xdg-mime query filetype'

# Setup default height and width for DMENU
alias dmenu="custom_dmenu"

# Alias for list themes
alias lst="ls /usr/share/themes && ls ~/.themes"

# Alias for list icons
alias lsi="ls /usr/share/icons && ls ~/.icons"